spring.application.name=bff-colegio
server.port=8080

services.notas.url=http://localhost:8082/api/notas
services.asistencia.url=http://localhost:8083/api/asistencias
services.auth.url=http://localhost:8081/api